name: My First Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Welcome Message
        run: echo "Hello World! This is my first GitHub Action!"
      
      - name: Display Current Time
        run: echo "Current time is $(date)"
