name: My First Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret
        run: echo "Cookie is: ${{ secrets.JD_COOKIE }}"
